version: '3'
services:
  web:
    # Build with dockerfile in the same folder?
    build: ./
    # ports:
    #   - 80:80
    # Start container automatically
    restart: always
    labels:
      # Enable Traefik for this specific "web" service
      - traefik.enable=true
      # Define the port inside of the Docker service to use
      - traefik.http.services.site.loadbalancer.server.port=8080
      # Make Traefik use this domain in HTTP
      - traefik.http.routers.site-http.entrypoints=http
      - traefik.http.routers.site-http.rule=Host(`www.murvel.lol`)
      # Use the traefik-public network (declared below)
      - traefik.docker.network=traefik-public
      # Make Traefik use this domain in HTTPS
      - traefik.http.routers.site-https.entrypoints=https
      - traefik.http.routers.site-https.rule=Host(`www.murvel.lol`)
      - traefik.http.routers.site-https.tls=true
      # Use the "le" (Let's Encrypt) resolver
      - traefik.http.routers.site-https.tls.certresolver=le
      # https-redirect middleware to redirect HTTP to HTTPS
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      # Middleware to redirect HTTP to HTTPS
      - traefik.http.routers.site-http.middlewares=https-redirect
    networks:
    # Use the public network created to be shared between Traefik and
    # any other service that needs to be publicly available with HTTPS
      - traefik-public
networks:
  traefik-public:
    external: true